name: CI & Release to Docker Hub

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
    tags:
      - "v*"

jobs:
  test:
    name: Lint, Vet & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"
          cache: false
      - name: gofmt (fail on diff)
        run: |
          diff=$(gofmt -l .)
          if [ -n "$diff" ]; then
            echo "$diff"
            exit 1
          fi
      - name: go vet
        run: go vet ./...
      - name: go test
        run: go test ./... -v

  publish_preview:
    name: Build Docker image (PR dry-run)
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    env:
      IMAGE_NAME: introleen/parcel-tracker
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate build context
        run: |
          test -f dockerfile || (echo "dockerfile missing" && exit 1)
          test -f go.mod || (echo "go.mod missing" && exit 1)
          test -f go.sum || (echo "go.sum missing" && exit 1)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=pr-${{ github.event.number }}
      - name: Build (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
      - name: Publish summary
        run: |
          {
            echo "###  PR dry-run build succeeded"
            echo "- Image (not pushed): \`${{ env.IMAGE_NAME }}\`"
            echo "- Tag: \`pr-${{ github.event.number }}\`"
          } >> "$GITHUB_STEP_SUMMARY"

  publish:
    name: Build & Push Docker image
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    env:
      IMAGE_NAME: introleen/parcel-tracker
      TAG_NAME: ${{ github.ref_name }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: introleen
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=raw,value=latest
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Verify manifest exists in registry
        run: docker buildx imagetools inspect "${IMAGE_NAME}:${TAG_NAME}"
      - name: Public pull test
        run: |
          docker logout || true
          docker pull "${IMAGE_NAME}:${TAG_NAME}"
      - name: Publish summary
        run: |
          {
            echo "### Docker Hub publish"
            echo "- Tag: \`${TAG_NAME}\`"
            echo "- Image: \`${IMAGE_NAME}\`"
            echo "- Hub: https://hub.docker.com/r/${IMAGE_NAME}"
            echo ""
            echo "#### Verify locally"
            echo "\`\`\`bash"
            echo "docker pull ${IMAGE_NAME}:${TAG_NAME}"
            echo "\`\`\`"
          } >> "$GITHUB_STEP_SUMMARY"
